// packages/vue3/test-app/Pages/Poll/RouterManual.vue
<script setup>
import { router } from '@jamesst20/inertia-vue3'

const { start, stop } = router.poll(
  500,
  {
    only: ['custom_prop'],
    onFinish() {
      console.log('hook poll finished')
    },
  },
  {
    autoStart: false,
  },
)
</script>

<template>
  <button @click="start">Start</button>
  <button @click="stop">Stop</button>
</template>

// packages/svelte/test-app/Pages/Poll/RouterManual.svelte
<script>
  import { router } from '@jamesst20/inertia-svelte'

  const { start, stop } = router.poll(
    500,
    {
      only: ['custom_prop'],
      onFinish() {
        console.log('hook poll finished')
      },
    },
    {
      autoStart: false,
    },
  )
</script>

<button on:click={() => start()}>Start</button>
<button on:click={() => stop()}>Stop</button>
