// packages/react/test-app/Pages/Poll/RouterManual.jsx
import { router } from '@jamesst20/inertia-react'
import { useRef } from 'react'

export default () => {
  const pollRef = useRef(
    router.poll(
      500,
      {
        only: ['custom_prop'],
        onFinish() {
          console.log('hook poll finished')
        },
      },
      {
        autoStart: false,
      },
    ),
  )

  return (
    <>
      <button onClick={pollRef.current.start}>Start</button>
      <button onClick={pollRef.current.stop}>Stop</button>
    </>
  )
}

// packages/svelte/test-app/Pages/Poll/RouterManual.svelte
<script>
  import { router } from '@jamesst20/inertia-svelte'

  const { start, stop } = router.poll(
    500,
    {
      only: ['custom_prop'],
      onFinish() {
        console.log('hook poll finished')
      },
    },
    {
      autoStart: false,
    },
  )
</script>

<button on:click={() => start()}>Start</button>
<button on:click={() => stop()}>Stop</button>
