// playgrounds/react/resources/js/Pages/Home.tsx
import { Head, Link } from '@jamesst20/inertia-react'
import Layout from '../Components/Layout'

const Home = () => {
  return (
    <>
      <Head title="Home" />
      <h1 className="text-3xl">Home</h1>
      <p className="mt-6">
        <Link href="/article#far-down" className="text-blue-700 underline">
          Link to bottom of article page
        </Link>
      </p>
    </>
  )
}

Home.layout = (page) => <Layout children={page} />

export default Home

// playgrounds/vue2/resources/js/Pages/Home.vue
<script>
import Layout from '../Components/Layout.vue'
export default { layout: Layout }
</script>

<script setup>
import { Head, Link } from '@jamesst20/inertia-vue2'
</script>

<template>
  <div>
    <Head title="Home" />
    <h1 class="text-3xl">Home</h1>
    <p class="mt-6">
      <Link href="/article#far-down" class="text-blue-700 underline">Link to bottom of article page</Link>
    </p>
  </div>
</template>
