// playgrounds/react/resources/js/Pages/Login.tsx
import { Head } from '@jamesst20/inertia-react'
import Layout from '../Components/Layout'

const Login = () => {
  return (
    <>
      <Head title="Login" />
      <h1 className="text-3xl">Login</h1>
      <p className="mt-6">
        You made a <code>POST</code> request to the logout endpoint and were redirected to the login page.
      </p>
    </>
  )
}

Login.layout = (page) => <Layout children={page} />

export default Login

// playgrounds/vue2/resources/js/Pages/Login.vue
<script>
import Layout from '../Components/Layout.vue'
export default { layout: Layout }
</script>

<script setup>
import { Head } from '@jamesst20/inertia-vue2'
</script>

<template>
  <div>
    <Head title="Login" />
    <h1 class="text-3xl">Login</h1>
    <p class="mt-6">
      You made a <code>POST</code> request to the logout endpoint and were redirected to the login page.
    </p>
  </div>
</template>
