// playgrounds/react/resources/js/Pages/Users.tsx
import { Head } from '@jamesst20/inertia-react'
import Layout from '../Components/Layout'

const Users = ({ users }) => {
  return (
    <>
      <Head title="Users" />
      <h1 className="text-3xl">Users</h1>
      <div className="mt-6 w-full max-w-2xl overflow-hidden rounded border shadow-sm">
        <table className="w-full text-left">
          <thead>
            <tr>
              <th className="px-4 py-2">Id</th>
              <th className="px-4 py-2">Name</th>
              <th className="px-4 py-2">Email</th>
            </tr>
          </thead>
          <tbody>
            {users.map((user) => (
              <tr key={user.id} className="border-t">
                <td className="px-4 py-2">{user.id}</td>
                <td className="px-4 py-2">{user.name}</td>
                <td className="px-4 py-2">{user.email}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  )
}

Users.layout = (page) => <Layout children={page} />

export default Users

// playgrounds/vue2/resources/js/Pages/Users.vue
<script>
import Layout from '../Components/Layout.vue'
export default { layout: Layout }
</script>

<script setup>
import { Head } from '@jamesst20/inertia-vue2'

defineProps({ users: Array })
</script>

<template>
  <div>
    <Head title="User" />
    <h1 class="text-3xl">Users</h1>
    <div class="mt-6 w-full max-w-2xl overflow-hidden rounded border shadow-sm">
      <table class="w-full text-left">
        <thead>
          <tr>
            <th class="px-4 py-2">Id</th>
            <th class="px-4 py-2">Name</th>
            <th class="px-4 py-2">Email</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="user in users" :key="user.id" class="border-t">
            <td class="px-4 py-2">{{ user.id }}</td>
            <td class="px-4 py-2">{{ user.name }}</td>
            <td class="px-4 py-2">{{ user.email }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
