// packages/svelte/test-app/Pages/DeferredProps/Page1.svelte
<script>
  import { Deferred, inertia } from '@jamesst20/inertia-svelte'

  export let foo
  export let bar
</script>

<Deferred data="foo">
  <svelte:fragment slot="fallback">
    <div>Loading foo...</div>
  </svelte:fragment>
  {foo.text}
</Deferred>

<Deferred data="bar">
  <svelte:fragment slot="fallback">
    <div>Loading bar...</div>
  </svelte:fragment>
  {bar.text}
</Deferred>

<a href="/deferred-props/page-1" use:inertia>Page 1</a>
<a href="/deferred-props/page-2" use:inertia>Page 2</a>

// packages/react/test-app/Pages/DeferredProps/Page1.jsx
import { Deferred, Link, usePage } from '@jamesst20/inertia-react'

const Foo = () => {
  const { foo } = usePage().props

  return foo.text
}

const Bar = () => {
  const { bar } = usePage().props

  return bar.text
}

export default () => {
  return (
    <>
      <Deferred data="foo" fallback={<div>Loading foo...</div>}>
        <Foo />
      </Deferred>

      <Deferred data="bar" fallback={<div>Loading bar...</div>}>
        <Bar />
      </Deferred>

      <Link href="/deferred-props/page-1">Page 1</Link>
      <Link href="/deferred-props/page-2">Page 2</Link>
    </>
  )
}
