// packages/svelte/test-app/Pages/Visits/Location.svelte
<script>
  import { router } from '@jamesst20/inertia-svelte'

  const locationVisit = () => {
    router.visit('/location')
  }
</script>

<div>
  <span class="text">This is the page that demonstrates location visits</span>

  <a href="#" on:click|preventDefault={locationVisit} class="example">Location visit</a>
</div>

// packages/react/test-app/Pages/Visits/Location.jsx
import { router } from '@jamesst20/inertia-react'

export default (props) => {
  const locationVisit = (e) => {
    e.preventDefault()
    router.visit('/location')
  }

  return (
    <div>
      <span className="text">This is the page that demonstrates location visits</span>

      <a href="#" onClick={locationVisit} className="example">
        Location visit
      </a>
    </div>
  )
}
