// packages/svelte/test-app/Pages/Visits/Method.svelte
<script>
  import { router } from '@jamesst20/inertia-svelte'

  const standardVisitMethod = () => {
    router.visit('/dump/get')
  }

  const specificVisitMethod = () => {
    router.visit('/dump/patch', {
      method: 'patch',
    })
  }

  const getMethod = () => {
    router.get('/dump/get')
  }

  const postMethod = () => {
    router.post('/dump/post')
  }

  const putMethod = () => {
    router.put('/dump/put')
  }

  const patchMethod = () => {
    router.patch('/dump/patch')
  }

  const deleteMethod = () => {
    router.delete('/dump/delete')
  }
</script>

<div>
  <span class="text">This is the page that demonstrates manual visit methods</span>

  <a href="#" on:click={standardVisitMethod} class="visit-get">Standard visit Link</a>
  <a href="#" on:click={specificVisitMethod} class="visit-specific">Specific visit Link</a>
  <a href="#" on:click={getMethod} class="get">GET Link</a>
  <a href="#" on:click={postMethod} class="post">POST Link</a>
  <a href="#" on:click={putMethod} class="put">PUT Link</a>
  <a href="#" on:click={patchMethod} class="patch">PATCH Link</a>
  <a href="#" on:click={deleteMethod} class="delete">DELETE Link</a>
</div>

// packages/react/test-app/Pages/Visits/Method.jsx
import { router } from '@jamesst20/inertia-react'

export default (props) => {
  const standardVisitMethod = (e) => {
    e.preventDefault()
    router.visit('/dump/get')
  }

  const specificVisitMethod = (e) => {
    e.preventDefault()
    router.visit('/dump/patch', { method: 'patch' })
  }

  const getMethod = (e) => {
    e.preventDefault()
    router.get('/dump/get')
  }

  const postMethod = (e) => {
    e.preventDefault()
    router.post('/dump/post')
  }

  const putMethod = (e) => {
    e.preventDefault()
    router.put('/dump/put')
  }

  const patchMethod = (e) => {
    e.preventDefault()
    router.patch('/dump/patch')
  }

  const deleteMethod = (e) => {
    e.preventDefault()
    router.delete('/dump/delete')
  }

  return (
    <div>
      <span className="text">This is the page that demonstrates manual visit methods</span>

      <a href="#" onClick={standardVisitMethod} className="visit-get">
        Standard visit Link
      </a>
      <a href="#" onClick={specificVisitMethod} className="visit-specific">
        Specific visit Link
      </a>
      <a href="#" onClick={getMethod} className="get">
        GET Link
      </a>
      <a href="#" onClick={postMethod} className="post">
        POST Link
      </a>
      <a href="#" onClick={putMethod} className="put">
        PUT Link
      </a>
      <a href="#" onClick={patchMethod} className="patch">
        PATCH Link
      </a>
      <a href="#" onClick={deleteMethod} className="delete">
        DELETE Link
      </a>
    </div>
  )
}
