// playgrounds/react/resources/js/Pages/Login.tsx
import { Head } from '@jamesst20/inertia-react'
import Layout from '../Components/Layout'

const Login = () => {
  return (
    <>
      <Head title="Login" />
      <h1 className="text-3xl">Login</h1>
      <p className="mt-6">
        You made a <code>POST</code> request to the logout endpoint and were redirected to the login page.
      </p>
    </>
  )
}

Login.layout = (page) => <Layout children={page} />

export default Login

// playgrounds/svelte/resources/js/Pages/Login.svelte
<script module>
  export { default as layout } from '../Components/Layout.svelte'
</script>

<script>
  export let appName
</script>

<svelte:head>
  <title>Login - {appName}</title>
</svelte:head>

<h1 class="text-3xl">Login</h1>

<p class="mt-6">You made a <code>POST</code> request to the logout endpoint and were redirected to the login page.</p>
