// playgrounds/react/resources/js/Pages/Users.tsx
import { Head } from '@jamesst20/inertia-react'
import Layout from '../Components/Layout'

const Users = ({ users }) => {
  return (
    <>
      <Head title="Users" />
      <h1 className="text-3xl">Users</h1>
      <div className="mt-6 w-full max-w-2xl overflow-hidden rounded border shadow-sm">
        <table className="w-full text-left">
          <thead>
            <tr>
              <th className="px-4 py-2">Id</th>
              <th className="px-4 py-2">Name</th>
              <th className="px-4 py-2">Email</th>
            </tr>
          </thead>
          <tbody>
            {users.map((user) => (
              <tr key={user.id} className="border-t">
                <td className="px-4 py-2">{user.id}</td>
                <td className="px-4 py-2">{user.name}</td>
                <td className="px-4 py-2">{user.email}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  )
}

Users.layout = (page) => <Layout children={page} />

export default Users

// playgrounds/svelte/resources/js/Pages/Users.svelte
<script module>
  export { default as layout } from '../Components/Layout.svelte'
</script>

<script>
  export let appName
  export let users
</script>

<svelte:head>
  <title>Users - {appName}</title>
</svelte:head>

<h1 class="text-3xl">Users</h1>

<div class="mt-6 w-full max-w-2xl overflow-hidden rounded border shadow-sm">
  <table class="w-full text-left">
    <thead>
      <tr>
        <th class="px-4 py-2">Id</th>
        <th class="px-4 py-2">Name</th>
        <th class="px-4 py-2">Email</th>
      </tr>
    </thead>
    <tbody>
      {#each users as user}
        <tr class="border-t">
          <td class="px-4 py-2">{user.id}</td>
          <td class="px-4 py-2">{user.name}</td>
          <td class="px-4 py-2">{user.email}</td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>
