// packages/vue3/test-app/Pages/ErrorModal.vue
<script setup>
import { router } from '@jamesst20/inertia-vue3'

const invalidVisit = () => {
  router.post('/non-inertia')
}

const invalidVisitJson = () => {
  router.post('/json')
}
</script>

<template>
  <div>
    <span @click="invalidVisit" class="invalid-visit">Invalid Visit</span>
    <span @click="invalidVisitJson" class="invalid-visit-json">Invalid Visit (JSON response)</span>
  </div>
</template>

// packages/react/test-app/Pages/ErrorModal.jsx
import { router } from '@jamesst20/inertia-react'

export default (props) => {
  const invalidVisit = () => {
    router.post('/non-inertia')
  }

  const invalidVisitJson = () => {
    router.post('/json')
  }

  return (
    <div>
      <span onClick={invalidVisit} className="invalid-visit">
        Invalid Visit
      </span>
      <span onClick={invalidVisitJson} className="invalid-visit-json">
        Invalid Visit (JSON response)
      </span>
    </div>
  )
}
