// packages/svelte/test-app/Pages/Home.svelte
<script>
  import { inertia, page, router } from '@jamesst20/inertia-svelte'
  import { onMount } from 'svelte'

  const visitsMethod = () => {
    router.visit('/visits/method')
  }

  const visitsReplace = () => {
    router.get('/visits/replace')
  }

  const redirect = () => {
    router.post('/redirect')
  }

  const redirectExternal = () => {
    router.post('/redirect-external')
  }

  onMount(() => {
    window._inertia_page_key = crypto.randomUUID()
    window._inertia_props = $page.props
    window._plugin_global_props = {}
  })
</script>

<div>
  <span class="text">This is the Test App Entrypoint page</span>

  <a href="/links/method" use:inertia class="links-method">Basic Links</a>
  <a href="/links/replace" use:inertia class="links-replace">'Replace' Links</a>

  <a href="#" on:click={visitsMethod} class="visits-method">Manual basic visits</a>
  <a href="#" on:click={visitsReplace} class="visits-replace">Manual 'Replace' visits</a>

  <button use:inertia={{ href: '/redirect', method: 'post' }} class="links-redirect">Internal Redirect Link</button>
  <a href="#" on:click={redirect} class="visits-redirect">Manual Redirect visit</a>

  <button use:inertia={{ href: '/redirect-external', method: 'post' }} class="links-redirect-external"
    >External Redirect Link</button
  >
  <a href="#" on:click={redirectExternal} class="visits-redirect-external">Manual External Redirect visit</a>
</div>

// packages/react/test-app/Pages/Home.jsx
import { Link, router } from '@jamesst20/inertia-react'

export default (props) => {
  const visitsMethod = (e) => {
    e.preventDefault()
    router.visit('/visits/method')
  }

  const visitsReplace = (e) => {
    e.preventDefault()
    router.get('/visits/replace')
  }

  const redirect = (e) => {
    e.preventDefault()
    router.post('/redirect')
  }

  const redirectExternal = (e) => {
    e.preventDefault()
    router.post('/redirect-external')
  }

  // window._inertia_page_key = getCurrentInstance().uid
  window._inertia_props = props
  // window._plugin_global_props = getCurrentInstance().appContext.config.globalProperties

  return (
    <div>
      <span className="text">This is the Test App Entrypoint page</span>

      <Link href="/links/method" className="links-method">
        Basic Links
      </Link>

      <Link href="/links/replace" className="links-replace">
        'Replace' Links
      </Link>

      <a href="#" onClick={visitsMethod} className="visits-method">
        Manual basic visits
      </a>

      <a href="#" onClick={visitsReplace} className="visits-replace">
        Manual 'Replace' visits
      </a>

      <Link href="/redirect" method="post" className="links-redirect">
        Internal Redirect Link
      </Link>
      <a href="#" onClick={redirect} className="visits-redirect">
        Manual Redirect visit
      </a>

      <Link href="/redirect-external" method="post" className="links-redirect-external">
        External Redirect Link
      </Link>

      <a href="#" onClick={redirectExternal} className="visits-redirect-external">
        Manual External Redirect visit
      </a>
    </div>
  )
}
