// packages/vue3/test-app/Pages/MergeProps.vue
<script setup lang="ts">
import { router } from '@jamesst20/inertia-vue3'

defineProps<{
  foo: number[]
  bar: number[]
}>()

const reloadIt = () => {
  router.reload({
    only: ['foo'],
  })
}

const getFresh = () => {
  router.reload({
    reset: ['foo'],
  })
}
</script>

<template>
  <div>bar count is {{ bar.length }}</div>
  <div>foo count is {{ foo.length }}</div>
  <button @click="reloadIt">Reload</button>
  <button @click="getFresh">Get Fresh</button>
</template>

// packages/react/test-app/Pages/MergeProps.jsx
import { router } from '@jamesst20/inertia-react'

export default ({ bar, foo }) => {
  const reloadIt = () => {
    router.reload({
      only: ['foo'],
    })
  }

  const getFresh = () => {
    router.reload({
      reset: ['foo'],
    })
  }

  return (
    <>
      <div>bar count is {bar.length}</div>
      <div>foo count is {foo.length}</div>
      <button onClick={reloadIt}>Reload</button>
      <button onClick={getFresh}>Get Fresh</button>
    </>
  )
}
