// packages/react/test-app/Pages/Links/Replace.jsx
import { Link } from '@jamesst20/inertia-react'

export default (props) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates replace on Links</span>

      <Link href="/dump/get" replace className="replace">
        [State] Replace: true
      </Link>
      <Link href="/dump/get" replace={false} className="replace-false">
        [State] Replace: false
      </Link>
    </div>
  )
}

// packages/vue3/test-app/Pages/Links/Replace.vue
<script setup>
import { Link } from '@jamesst20/inertia-vue3'
</script>

<template>
  <div>
    <span class="text">This is the links page that demonstrates replace on Links</span>

    <Link href="/dump/get" replace class="replace">[State] Replace: true</Link>
    <Link href="/dump/get" :replace="false" class="replace-false">[State] Replace: false</Link>
  </div>
</template>
