// packages/react/test-app/Pages/DeferredProps/Page2.jsx
import { Deferred, Link, usePage } from '@jamesst20/inertia-react'

const Baz = () => {
  const { baz } = usePage().props

  return baz
}

const Qux = () => {
  const { qux } = usePage().props

  return qux
}

const Both = () => {
  const { baz, qux } = usePage().props

  return `both ${baz} and ${qux}`
}
export default () => {
  return (
    <>
      <Deferred data="baz" fallback={<div>Loading baz...</div>}>
        <Baz />
      </Deferred>

      <Deferred data="qux" fallback={<div>Loading qux...</div>}>
        <Qux />
      </Deferred>

      <Deferred data={['baz', 'qux']} fallback={<div>Loading baz and qux...</div>}>
        <Both />
      </Deferred>

      <Link href="/deferred-props/page-2">Page 2</Link>
    </>
  )
}

// packages/svelte/test-app/Pages/DeferredProps/Page2.svelte
<script>
  import { Deferred } from '@jamesst20/inertia-svelte'

  export let baz
  export let qux
</script>

<Deferred data="baz">
  <div slot="fallback">Loading baz...</div>
  {baz}
</Deferred>

<Deferred data="qux">
  <div slot="fallback">Loading qux...</div>
  {qux}
</Deferred>

<Deferred data={['baz', 'qux']}>
  <div slot="fallback">Loading baz and qux...</div>
  both {baz} and {qux}
</Deferred>
