// packages/vue3/test-app/Pages/Remember/Components/ComponentB.vue
<script setup>
import { useRemember } from '@jamesst20/inertia-vue3'
import { ref } from 'vue'

const untracked = ref('')

const data = useRemember(
  {
    name: '',
    remember: false,
  },
  'Example/ComponentB',
)
</script>

<template>
  <div>
    <span>This component uses a callback-style 'key' for the remember functionality.</span>
    <label>
      Full Name
      <input type="text" class="b-name" name="full_name" v-model="data.name" />
    </label>
    <label>
      Remember Me
      <input type="checkbox" class="b-remember" name="remember" v-model="data.remember" />
    </label>
    <label>
      Remember Me
      <input type="text" class="b-untracked" name="untracked" v-model="untracked" />
    </label>
  </div>
</template>

// packages/svelte/test-app/Pages/Remember/Components/ComponentB.svelte
<script>
  import { useRemember } from '@jamesst20/inertia-svelte'

  let untracked = ''

  const data = useRemember(
    {
      name: '',
      remember: false,
    },
    'Example/ComponentB',
  )
</script>

<div {...$$restProps}>
  <span>This component uses a string 'key' for the remember functionality.</span>
  <label>
    Full Name
    <input type="text" class="b-name" name="full_name" bind:value={$data.name} />
  </label>
  <label>
    Remember Me
    <input type="checkbox" class="b-remember" name="remember" bind:checked={$data.remember} />
  </label>
  <label>
    Remember Me
    <input type="text" class="b-untracked" name="untracked" bind:value={untracked} />
  </label>
</div>
