// packages/svelte/test-app/Pages/Links/Data/AutoConverted.svelte
<script>
  import { inertia } from '@jamesst20/inertia-svelte'

  const linkData = {
    file: new File([], 'example.jpg'),
    foo: 'bar',
  }
</script>

<div>
  <span class="text"
    >This is the links page that demonstrates the automatic conversion of plain objects to form-data</span
  >

  <a href="/dump/get" use:inertia={{ method: 'GET', data: linkData }} class="get">GET Link</a>
  <button use:inertia={{ method: 'POST', href: '/dump/post', data: linkData }} class="post">POST Link</button>
  <button use:inertia={{ method: 'PUT', href: '/dump/put', data: linkData }} class="put">PUT Link</button>
  <button use:inertia={{ method: 'PATCH', href: '/dump/patch', data: linkData }} class="patch">PATCH Link</button>
  <button use:inertia={{ method: 'DELETE', href: '/dump/delete', data: linkData }} class="delete">DELETE Link</button>
</div>

// packages/react/test-app/Pages/Links/Data/AutoConverted.jsx
import { Link } from '@jamesst20/inertia-react'

export default (props) => {
  const linkData = { file: new File([], 'example.jpg'), foo: 'bar' }

  return (
    <div>
      <span className="text">
        This is the links page that demonstrates the automatic conversion of plain objects to form-data
      </span>

      <Link method="get" href="/dump/get" data={linkData} className="get">
        GET Link
      </Link>
      <Link as="button" method="post" href="/dump/post" data={linkData} className="post">
        POST Link
      </Link>
      <Link as="button" method="put" href="/dump/put" data={linkData} className="put">
        PUT Link
      </Link>
      <Link as="button" method="patch" href="/dump/patch" data={linkData} className="patch">
        PATCH Link
      </Link>
      <Link as="button" method="delete" href="/dump/delete" data={linkData} className="delete">
        DELETE Link
      </Link>
    </div>
  )
}
