// packages/vue3/test-app/Pages/Links/Data/AutoConverted.vue
<script setup>
import { Link } from '@jamesst20/inertia-vue3'

const linkData = {
  file: new File([], 'example.jpg'),
  foo: 'bar',
}
</script>

<template>
  <div>
    <span class="text"
      >This is the links page that demonstrates the automatic conversion of plain objects to form-data</span
    >

    <Link method="GET" href="/dump/get" :data="linkData" class="get">GET Link</Link>
    <Link as="button" method="POST" href="/dump/post" :data="linkData" class="post">POST Link</Link>
    <Link as="button" method="PUT" href="/dump/put" :data="linkData" class="put">PUT Link</Link>
    <Link as="button" method="PATCH" href="/dump/patch" :data="linkData" class="patch">PATCH Link</Link>
    <Link as="button" method="DELETE" href="/dump/delete" :data="linkData" class="delete">DELETE Link</Link>
  </div>
</template>

// packages/react/test-app/Pages/Links/Data/AutoConverted.jsx
import { Link } from '@jamesst20/inertia-react'

export default (props) => {
  const linkData = { file: new File([], 'example.jpg'), foo: 'bar' }

  return (
    <div>
      <span className="text">
        This is the links page that demonstrates the automatic conversion of plain objects to form-data
      </span>

      <Link method="get" href="/dump/get" data={linkData} className="get">
        GET Link
      </Link>
      <Link as="button" method="post" href="/dump/post" data={linkData} className="post">
        POST Link
      </Link>
      <Link as="button" method="put" href="/dump/put" data={linkData} className="put">
        PUT Link
      </Link>
      <Link as="button" method="patch" href="/dump/patch" data={linkData} className="patch">
        PATCH Link
      </Link>
      <Link as="button" method="delete" href="/dump/delete" data={linkData} className="delete">
        DELETE Link
      </Link>
    </div>
  )
}
