// packages/react/test-app/Pages/Remember/Default.jsx
import { Link } from '@jamesst20/inertia-react'
import { useState } from 'react'

export default (props) => {
  const [name, setName] = useState('')
  const [remember, setRemember] = useState(false)
  const [untracked, setUntracked] = useState('')

  return (
    <div>
      <label>
        Full Name
        <input type="text" id="name" name="full_name" value={name} onChange={(e) => setName(e.target.value)} />
      </label>
      <label>
        Remember Me
        <input
          type="checkbox"
          id="remember"
          name="remember"
          checked={remember}
          onChange={(e) => setRemember(e.target.checked)}
        />
      </label>
      <label>
        Untracked
        <input
          type="text"
          id="untracked"
          name="untracked"
          value={untracked}
          onChange={(e) => setUntracked(e.target.value)}
        />
      </label>

      <Link href="/dump/get" className="link">
        Navigate away
      </Link>
    </div>
  )
}

// packages/svelte/test-app/Pages/Remember/Default.svelte
<script>
  import { inertia } from '@jamesst20/inertia-svelte'

  let name = ''
  let remember = false
  let untracked = ''
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="full_name" bind:value={name} />
  </label>
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={remember} />
  </label>
  <label>
    Untracked
    <input type="text" id="untracked" name="untracked" bind:value={untracked} />
  </label>

  <a href="/dump/get" use:inertia class="link">Navigate away</a>
</div>
