// packages/react/test-app/Pages/Remember/MultipleComponents.jsx
import { Link, useRemember } from '@jamesst20/inertia-react'
import { useState } from 'react'
import ComponentA from './Components/ComponentA'
import ComponentB from './Components/ComponentB'

export default (props) => {
  const [untracked, setUntracked] = useState('')

  const [form, setForm] = useRemember({ name: '', remember: false })

  return (
    <div>
      <label>
        Full Name
        <input
          type="text"
          id="name"
          name="full_name"
          value={form.name}
          onChange={(e) => setForm({ ...form, name: e.target.value })}
        />
      </label>
      <label>
        Remember Me
        <input
          type="checkbox"
          id="remember"
          name="remember"
          checked={form.remember}
          onChange={(e) => setForm({ ...form, remember: e.target.checked })}
        />
      </label>
      <label>
        Untracked
        <input
          type="text"
          id="untracked"
          name="untracked"
          value={untracked}
          onChange={(e) => setUntracked(e.target.value)}
        />
      </label>

      <ComponentA className="component-a" />
      <ComponentB className="component-b" />

      <Link href="/dump/get" className="link">
        Navigate away
      </Link>
      <a href="/non-inertia" className="off-site">
        Navigate off-site
      </a>
    </div>
  )
}

// packages/svelte/test-app/Pages/Remember/MultipleComponents.svelte
<script>
  import ComponentA from '@/Pages/Remember/Components/ComponentA.svelte'
  import ComponentB from '@/Pages/Remember/Components/ComponentB.svelte'
  import { inertia, useRemember } from '@jamesst20/inertia-svelte'

  let untracked = ''

  const form = useRemember({
    name: '',
    remember: false,
  })
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="full_name" bind:value={$form.name} />
  </label>
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={$form.remember} />
  </label>
  <label>
    Untracked
    <input type="text" id="untracked" name="untracked" bind:value={untracked} />
  </label>

  <ComponentA class="component-a" />
  <ComponentB class="component-b" />

  <a href="/dump/get" use:inertia class="link">Navigate away</a>
  <a href="/non-inertia" class="off-site">Navigate off-site</a>
</div>
