// packages/react/src/WhenVisible.ts
import { ReloadOptions, router } from '@jamesst20/inertia-core'
import { createElement, ReactElement, useEffect, useRef, useState } from 'react'

interface WhenVisibleProps {
  children: ReactElement | number | string
  fallback: ReactElement | number | string
  data: string | string[]
  params?: ReloadOptions
  buffer?: number
  as?: string
  always?: boolean
}

const WhenVisible = ({ children, data, params, buffer, as, always, fallback }: WhenVisibleProps) => {
  always = always ?? false
  as = as ?? 'div'
  fallback = fallback ?? null

  const [loaded, setLoaded] = useState(false)
  const [fetching, setFetching] = useState(false)
  const observer = useRef<IntersectionObserver | null>(null)
  const ref = useRef<HTMLDivElement>(null)

  const getReloadParams = (): Partial<ReloadOptions> => {
    if (data) {
      return {
        only: (Array.isArray(data) ? data : [data]) as string[],
      }
    }

    if (!params) {
      throw new Error('You must provide either a `data` or `params` prop.')
    }

    return params
  }

  useEffect(() => {
    if (!ref.current) {
      return
    }

    observer.current = new IntersectionObserver(
      (entries) => {
        if (!entries[0].isIntersecting) {
          return
        }

        if (!always) {
          observer.current?.disconnect()
        }

        if (fetching) {
          return
        }

        setFetching(true)

        const reloadParams = getReloadParams()

        router.reload({
          ...reloadParams,
          onStart: (e) => {
            setFetching(true)
            reloadParams.onStart?.(e)
          },
          onFinish: (e) => {
            setLoaded(true)
            setFetching(false)
            reloadParams.onFinish?.(e)
          },
        })
      },
      {
        rootMargin: `${buffer || 0}px`,
      },
    )

    observer.current.observe(ref.current)

    return () => {
      observer.current?.disconnect()
    }
  }, [ref])

  if (always || !loaded) {
    return createElement(
      as,
      {
        props: null,
        ref,
      },
      loaded ? children : fallback,
    )
  }

  return loaded ? children : null
}

WhenVisible.displayName = 'InertiaWhenVisible'

export default WhenVisible

// packages/svelte/src/components/WhenVisible.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'

  type WhenVisibleProps =  {
    data: string | string[]
    params?: ReloadOptions
    buffer?: number
    as?: keyof HTMLElementTagNameMap
    always?: boolean
    children: Snippet
    fallback: Snippet
  }
</script>

<script lang="ts">
  import { router, type ReloadOptions } from '@jamesst20/inertia-core'

  let { 
    data = '', 
    params = {}, 
    buffer = 0, 
    as = 'div', 
    always = false, 
    children, 
    fallback 
  }: WhenVisibleProps = $props()

  let loaded = $state(false)
  let fetching = $state(false)
  let el = $state<HTMLElement>()

  $effect(() => {
    if (!el) {
      return
    }

    const observer = new IntersectionObserver(
      (entries) => {
        if (!entries[0].isIntersecting) {
          return
        }

        if (!always) {
          observer?.disconnect()
        }

        if (fetching) {
          return
        }

        fetching = true

        const reloadParams = getReloadParams()

        router.reload({
          ...reloadParams,
          onStart: (event) => {
            fetching = true
            reloadParams.onStart?.(event)
          },
          onFinish: (event) => {
            loaded = true
            fetching = false
            reloadParams.onFinish?.(event)
          },
        })
      },
      {
        rootMargin: `${buffer}px`,
      },
    )

    observer.observe(el)

    return () => {
      observer?.disconnect()
    }
  })

  function getReloadParams(): Partial<ReloadOptions> {
    if (data !== '') {
      return {
        only: (Array.isArray(data) ? data : [data]) as string[],
      }
    }

    if (!params.data) {
      throw new Error('You must provide either a `data` or `params` prop.')
    }

    return params
  }
</script>

{#if always || !loaded}
  <svelte:element this={as} bind:this={el} />
{/if}

{#if loaded}
  {@render children?.()}
{:else}
  {@render fallback?.()}
{/if}
