// playgrounds/vue2/resources/js/Components/Layout.vue
<script setup>
import { Link, usePage } from '@jamesst20/inertia-vue2'
import { computed } from 'vue'

const page = usePage()

const appName = computed(() => page.props.appName)
</script>

<template>
  <div>
    <nav class="flex items-center space-x-6 bg-slate-800 px-10 py-6 text-white">
      <div class="rounded-lg bg-slate-700 px-4 py-1">{{ appName }}</div>
      <Link href="/" class="hover:underline">Home</Link>
      <Link href="/users" class="hover:underline">Users</Link>
      <Link href="/article" class="hover:underline">Article</Link>
      <Link href="/form" class="hover:underline">Form</Link>
      <Link href="/logout" method="post" as="button" type="button" class="hover:underline">Logout</Link>
    </nav>
    <main class="px-10 py-8">
      <slot />
    </main>
  </div>
</template>

// playgrounds/react/resources/js/Components/Layout.tsx
import { Link, usePage } from '@jamesst20/inertia-react'

export default function Layout({ children }) {
  const { appName } = usePage<{ appName: string }>().props

  return (
    <>
      <nav className="flex items-center space-x-6 bg-slate-800 px-10 py-6 text-white">
        <div className="rounded-lg bg-slate-700 px-4 py-1">{appName}</div>
        <Link href="/" className="hover:underline">
          Home
        </Link>
        <Link href="/users" className="hover:underline">
          Users
        </Link>
        <Link href="/article" className="hover:underline">
          Article
        </Link>
        <Link href="/form" className="hover:underline">
          Form
        </Link>
        <Link href="/logout" method="post" as="button" type="button" className="hover:underline">
          Logout
        </Link>
      </nav>
      <main className="px-10 py-8">{children}</main>
    </>
  )
}
