// packages/vue3/test-app/Pages/Visits/AutomaticCancellation.vue
<script setup>
import { router } from '@jamesst20/inertia-vue3'

const visit = () => {
  router.get(
    '/sleep',
    {},
    {
      onStart: () => console.log('started'),
      onCancel: () => console.log('cancelled'),
    },
  )
}
</script>

<template>
  <div>
    <span class="text">This is the page that demonstrates that only one visit can be active at a time</span>
    <a href="#" @click="visit" class="visit">Link</a>
  </div>
</template>

// packages/svelte/test-app/Pages/Visits/AutomaticCancellation.svelte
<script>
  import { router } from '@jamesst20/inertia-svelte'

  const visit = () => {
    router.get(
      '/sleep',
      {},
      {
        onStart: () => console.log('started'),
        onCancel: () => console.log('cancelled'),
      },
    )
  }
</script>

<div>
  <span class="text">This is the page that demonstrates that only one visit can be active at a time</span>
  <a href="#" on:click={visit} class="visit">Link</a>
</div>
