// packages/react/test-app/Pages/Links/Location.jsx
import { Link } from '@jamesst20/inertia-react'

export default (props) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates location visits inertia-links</span>

      <Link href="/location" replace className="example">
        Location visit
      </Link>
    </div>
  )
}

// packages/svelte/test-app/Pages/Visits/Location.svelte
<script>
  import { router } from '@jamesst20/inertia-svelte'

  const locationVisit = () => {
    router.visit('/location')
  }
</script>

<div>
  <span class="text">This is the page that demonstrates location visits</span>

  <a href="#" on:click|preventDefault={locationVisit} class="example">Location visit</a>
</div>
