// packages/react/test-app/Pages/Links/Headers.jsx
import { Link } from '@jamesst20/inertia-react'
export default (props) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates passing custom headers</span>
      <Link href="/dump/get" className="default">
        Standard visit Link
      </Link>

      <Link method="get" href="/dump/get" headers={{ foo: 'bar' }} className="custom">
        GET Link
      </Link>
      <Link
        as="button"
        method="post"
        href="/dump/post"
        headers={{ bar: 'baz', 'X-Requested-With': 'custom' }}
        className="overridden"
      >
        POST Link
      </Link>
    </div>
  )
}

// packages/svelte/test-app/Pages/Links/Headers.svelte
<script>
  import { inertia } from '@jamesst20/inertia-svelte'
</script>

<div>
  <span class="text">This is the links page that demonstrates passing custom headers</span>
  <a href="/dump/get" use:inertia class="default">Standard visit Link</a>

  <a href="/dump/get" use:inertia={{ method: 'get', headers: { foo: 'bar' } }} class="custom">GET Link</a>
  <button
    use:inertia={{ method: 'post', href: '/dump/post', headers: { bar: 'baz', 'X-Requested-With': 'custom' } }}
    class="overridden">POST Link</button
  >
</div>
