// packages/vue3/test-app/Pages/Links/UrlFragments.vue
<script setup>
import { Link } from '@jamesst20/inertia-vue3'
import { onMounted, ref } from 'vue'

const documentScrollTop = ref(0)
const documentScrollLeft = ref(0)

onMounted(() => {
  document.addEventListener('scroll', handleScrollEvent)
})

const handleScrollEvent = () => {
  documentScrollTop.value = document.documentElement.scrollTop
  documentScrollLeft.value = document.documentElement.scrollLeft
}
</script>

<template>
  <div>
    <span class="text">This is the links page that demonstrates url fragment behaviour</span>
    <div style="width: 200vw; height: 200vh; margin-top: 50vh">
      <!-- prettier-ignore -->
      <div class="document-position">Document scroll position is {{ documentScrollLeft }} & {{ documentScrollTop }}</div>
      <Link href="/links/url-fragments#target" class="basic">Basic link</Link>
      <Link href="#target" class="fragment">Fragment link</Link>
      <Link href="/links/url-fragments#non-existent-fragment" class="non-existent-fragment"
        >Non-existent fragment link</Link
      >

      <div id="target">This is the element with id 'target'</div>
    </div>
  </div>
</template>

// packages/svelte/test-app/Pages/Links/UrlFragments.svelte
<script>
  import { inertia } from '@jamesst20/inertia-svelte'

  let documentScrollTop = 0
  let documentScrollLeft = 0

  const handleScrollEvent = () => {
    documentScrollTop = document.documentElement.scrollTop
    documentScrollLeft = document.documentElement.scrollLeft
  }
</script>

<svelte:document on:scroll={handleScrollEvent} />

<div>
  <span class="text">This is the links page that demonstrates url fragment behaviour</span>
  <div style="width: 200vw; height: 200vh; margin-top: 50vh">
    <!-- prettier-ignore -->
    <div class="document-position">Document scroll position is {documentScrollLeft} & {documentScrollTop}</div>
    <a href="/links/url-fragments#target" use:inertia class="basic">Basic link</a>
    <a href="#target" use:inertia class="fragment">Fragment link</a>
    <a href="/links/url-fragments#non-existent-fragment" use:inertia class="non-existent-fragment"
      >Non-existent fragment link</a
    >

    <div id="target">This is the element with id 'target'</div>
  </div>
</div>
