// packages/vue3/test-app/Pages/PersistentLayouts/Shorthand/Nested/PageA.vue
<script>
import NestedLayout from '@/Layouts/NestedLayout.vue'
import SiteLayout from '@/Layouts/SiteLayout.vue'

export default {
  layout: [SiteLayout, NestedLayout],
}
</script>

<script setup>
import { Link, usePage } from '@jamesst20/inertia-vue3'
window._inertia_page_props = usePage().props
</script>

<template>
  <div>
    <span class="text">Nested Persistent Layout - Page A</span>
    <Link href="/persistent-layouts/shorthand/nested/page-b">Page B</Link>
  </div>
</template>

// packages/svelte/test-app/Pages/PersistentLayouts/Shorthand/Nested/PageA.svelte
<script module>
  import NestedLayout from '@/Layouts/NestedLayout.svelte'
  import SiteLayout from '@/Layouts/SiteLayout.svelte'

  export const layout = [SiteLayout, NestedLayout]
</script>

<script>
  import { inertia, page } from '@jamesst20/inertia-svelte'

  window._inertia_page_props = $page.props
</script>

<div>
  <span class="text">Nested Persistent Layout - Page A</span>
  <a href="/persistent-layouts/shorthand/nested/page-b" use:inertia>Page B</a>
</div>
