// packages/react/test-app/Pages/PersistentLayouts/Shorthand/Nested/PageB.jsx
import NestedLayout from '@/Layouts/NestedLayout.jsx'
import SiteLayout from '@/Layouts/SiteLayout.jsx'
import { Link, usePage } from '@jamesst20/inertia-react'

const PageB = (props) => {
  window._inertia_page_props = usePage().props

  return (
    <div>
      <span className="text">Nested Persistent Layout - Page B</span>
      <Link href="/persistent-layouts/shorthand/nested/page-a">Page A</Link>
    </div>
  )
}

PageB.layout = (page) => {
  return (
    <SiteLayout>
      <NestedLayout children={page} />
    </SiteLayout>
  )
}

export default PageB

// packages/svelte/test-app/Pages/PersistentLayouts/Shorthand/Nested/PageB.svelte
<script module>
  import NestedLayout from '@/Layouts/NestedLayout.svelte'
  import SiteLayout from '@/Layouts/SiteLayout.svelte'

  export const layout = [SiteLayout, NestedLayout]
</script>

<script>
  import { inertia, page } from '@jamesst20/inertia-svelte'

  window._inertia_page_props = $page.props
</script>

<div>
  <span class="text">Nested Persistent Layout - Page B</span>
  <a href="/persistent-layouts/shorthand/nested/page-a" use:inertia>Page A</a>
</div>
