// packages/svelte/test-app/Pages/Remember/FormHelper/Default.svelte
<script>
  import { inertia, useForm } from '@jamesst20/inertia-svelte'

  let untracked = ''

  const form = useForm({
    name: 'foo',
    handle: 'example',
    remember: false,
  })

  const submit = () => {
    $form.post('/remember/form-helper/default')
  }
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="name" bind:value={$form.name} />
  </label>
  {#if $form.errors.name}
    <span class="name_error">{$form.errors.name}</span>
  {/if}
  <label>
    Handle
    <input type="text" id="handle" name="handle" bind:value={$form.handle} />
  </label>
  {#if $form.errors.handle}
    <span class="handle_error">{$form.errors.handle}</span>
  {/if}
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={$form.remember} />
  </label>
  {#if $form.errors.remember}
    <span class="remember_error">{$form.errors.remember}</span>
  {/if}
  <label>
    Untracked
    <input type="text" id="untracked" name="untracked" bind:value={untracked} />
  </label>

  <button on:click={submit} class="submit">Submit form</button>

  <a href="/dump/get" use:inertia class="link">Navigate away</a>
</div>

// packages/vue3/test-app/Pages/Remember/FormHelper/Default.vue
<script setup>
import { Link, useForm } from '@jamesst20/inertia-vue3'
import { ref } from 'vue'

const untracked = ref('')

const form = useForm({
  name: 'foo',
  handle: 'example',
  remember: false,
})

const submit = () => {
  form.post('/remember/form-helper/default')
}
</script>

<template>
  <div>
    <label>
      Full Name
      <input type="text" id="name" name="name" v-model="form.name" />
    </label>
    <span class="name_error" v-if="form.errors.name">{{ form.errors.name }}</span>
    <label>
      Handle
      <input type="text" id="handle" name="handle" v-model="form.handle" />
    </label>
    <span class="handle_error" v-if="form.errors.handle">{{ form.errors.handle }}</span>
    <label>
      Remember Me
      <input type="checkbox" id="remember" name="remember" v-model="form.remember" />
    </label>
    <span class="remember_error" v-if="form.errors.remember">{{ form.errors.remember }}</span>
    <label>
      Untracked
      <input type="text" id="untracked" name="untracked" v-model="untracked" />
    </label>

    <button @click="submit" class="submit">Submit form</button>

    <Link href="/dump/get" class="link">Navigate away</Link>
  </div>
</template>
