// packages/react/test-app/Pages/PersistentLayouts/RenderFunction/Simple/PageB.jsx
import SiteLayout from '@/Layouts/SiteLayout.jsx'
import { Link } from '@jamesst20/inertia-react'

const PageB = (props) => {
  return (
    <div>
      <span className="text">Simple Persistent Layout - Page B</span>
      <Link href="/persistent-layouts/render-function/simple/page-a">Page A</Link>
    </div>
  )
}

PageB.layout = (page) => <SiteLayout children={page} />

export default PageB

// packages/vue3/test-app/Pages/PersistentLayouts/RenderFunction/Simple/PageB.vue
<script>
import Layout from '@/Layouts/SiteLayout.vue'

export default {
  layout: (h, page) => h(Layout, [page]),
}
</script>

<script setup>
import { Link } from '@jamesst20/inertia-vue3'
</script>

<template>
  <div>
    <span class="text">Simple Persistent Layout - Page B</span>
    <Link href="/persistent-layouts/render-function/simple/page-a">Page A</Link>
  </div>
</template>
