// packages/svelte/test-app/Pages/PersistentLayouts/RenderFunction/Simple/PageA.svelte
<script module>
  import SiteLayout from '@/Layouts/SiteLayout.svelte'

  export const layout = (h, page) => h(SiteLayout, [page])
</script>

<script>
  import { inertia } from '@jamesst20/inertia-svelte'
</script>

<div>
  <span class="text">Simple Persistent Layout - Page A</span>
  <a href="/persistent-layouts/render-function/simple/page-b" use:inertia>Page B</a>
</div>

// packages/vue3/test-app/Pages/PersistentLayouts/RenderFunction/Simple/PageA.vue
<script>
import Layout from '@/Layouts/SiteLayout.vue'

export default {
  layout: (h, page) => h(Layout, [page]),
}
</script>

<script setup>
import { Link } from '@jamesst20/inertia-vue3'
</script>

<template>
  <div>
    <span class="text">Simple Persistent Layout - Page A</span>
    <Link href="/persistent-layouts/render-function/simple/page-b">Page B</Link>
  </div>
</template>
