// packages/svelte/test-app/Pages/PersistentLayouts/Shorthand/Simple/PageB.svelte
<script module>
  import SiteLayout from '@/Layouts/SiteLayout.svelte'

  export const layout = SiteLayout
</script>

<script>
  import { inertia, page } from '@jamesst20/inertia-svelte'

  window._inertia_page_props = $page.props
</script>

<div>
  <span class="text">Simple Persistent Layout - Page B</span>
  <a href="/persistent-layouts/shorthand/simple/page-a" use:inertia>Page A</a>
</div>

// packages/react/test-app/Pages/PersistentLayouts/Shorthand/Simple/PageB.jsx
import SiteLayout from '@/Layouts/SiteLayout.jsx'
import { Link, usePage } from '@jamesst20/inertia-react'

const PageB = (props) => {
  window._inertia_page_props = usePage().props

  return (
    <div>
      <span className="text">Simple Persistent Layout - Page B</span>
      <Link href="/persistent-layouts/shorthand/simple/page-a">Page A</Link>
    </div>
  )
}

PageB.layout = (page) => <SiteLayout children={page} />

export default PageB
