// packages/vue3/test-app/Pages/PersistentLayouts/RenderFunction/Nested/PageB.vue
<script>
import NestedLayout from '@/Layouts/NestedLayout.vue'
import SiteLayout from '@/Layouts/SiteLayout.vue'

export default {
  layout: (h, page) => {
    return h(SiteLayout, [h(NestedLayout, [page])])
  },
}
</script>

<script setup>
import { Link } from '@jamesst20/inertia-vue3'
</script>

<template>
  <div>
    <span class="text">Nested Persistent Layout - Page B</span>
    <Link href="/persistent-layouts/render-function/nested/page-a">Page A</Link>
  </div>
</template>

// packages/svelte/test-app/Pages/PersistentLayouts/RenderFunction/Nested/PageB.svelte
<script module>
  import NestedLayout from '@/Layouts/NestedLayout.svelte'
  import SiteLayout from '@/Layouts/SiteLayout.svelte'

  export const layout = (h, page) => {
    return h(SiteLayout, [h(NestedLayout, [page])])
  }
</script>

<script>
  import { inertia } from '@jamesst20/inertia-svelte'
</script>

<div>
  <span class="text">Nested Persistent Layout - Page B</span>
  <a href="/persistent-layouts/render-function/nested/page-a" use:inertia>Page A</a>
</div>
