// packages/react/test-app/Pages/Remember/FormHelper/Default.jsx
import { Link, useForm } from '@jamesst20/inertia-react'
import { useState } from 'react'

export default (props) => {
  const [untracked, setUntracked] = useState('')

  const form = useForm({ name: 'foo', handle: 'example', remember: false })

  const submit = () => {
    form.post('/remember/form-helper/default')
  }

  return (
    <div>
      <label>
        Full Name
        <input
          type="text"
          id="name"
          name="name"
          value={form.data.name}
          onChange={(e) => form.setData('name', e.target.value)}
        />
      </label>
      {form.errors.name && <span className="name_error">{form.errors.name}</span>}
      <label>
        Handle
        <input
          type="text"
          id="handle"
          name="handle"
          value={form.data.handle}
          onChange={(e) => form.setData('handle', e.target.value)}
        />
      </label>
      {form.errors.handle && <span className="handle_error">{form.errors.handle}</span>}
      <label>
        Remember Me
        <input
          type="checkbox"
          id="remember"
          name="remember"
          checked={form.data.remember}
          onChange={(e) => form.setData('remember', e.target.checked)}
        />
      </label>
      {form.errors.remember && <span className="remember_error">{form.errors.remember}</span>}
      <label>
        Untracked
        <input
          type="text"
          id="untracked"
          name="untracked"
          value={untracked}
          onChange={(e) => setUntracked(e.target.value)}
        />
      </label>

      <button onClick={submit} className="submit">
        Submit form
      </button>

      <Link href="/dump/get" className="link">
        Navigate away
      </Link>
    </div>
  )
}

// packages/svelte/test-app/Pages/Remember/FormHelper/Default.svelte
<script>
  import { inertia, useForm } from '@jamesst20/inertia-svelte'

  let untracked = ''

  const form = useForm({
    name: 'foo',
    handle: 'example',
    remember: false,
  })

  const submit = () => {
    $form.post('/remember/form-helper/default')
  }
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="name" bind:value={$form.name} />
  </label>
  {#if $form.errors.name}
    <span class="name_error">{$form.errors.name}</span>
  {/if}
  <label>
    Handle
    <input type="text" id="handle" name="handle" bind:value={$form.handle} />
  </label>
  {#if $form.errors.handle}
    <span class="handle_error">{$form.errors.handle}</span>
  {/if}
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={$form.remember} />
  </label>
  {#if $form.errors.remember}
    <span class="remember_error">{$form.errors.remember}</span>
  {/if}
  <label>
    Untracked
    <input type="text" id="untracked" name="untracked" bind:value={untracked} />
  </label>

  <button on:click={submit} class="submit">Submit form</button>

  <a href="/dump/get" use:inertia class="link">Navigate away</a>
</div>
