// packages/svelte/test-app/Pages/History/Page.svelte
<script>
  import { inertia, router } from '@jamesst20/inertia-svelte'

  export let pageNumber
    export let multiByte
</script>

<a href="/history/1" use:inertia>Page 1</a>
<a href="/history/2" use:inertia>Page 2</a>
<a href="/history/3" use:inertia>Page 3</a>
<a href="/history/4" use:inertia>Page 4</a>
<a href="/history/5" use:inertia>Page 5</a>

<button on:click={() => router.clearHistory()}>Clear History</button>

<div>This is page {pageNumber}.</div>
<div>Multi byte character: { multiByte }</div>

// packages/react/test-app/Pages/History/Page.jsx
import { Link, router } from '@jamesst20/inertia-react'

export default ({ pageNumber, multiByte }) => {
  const clearHistory = () => {
    router.clearHistory()
  }

  return (
    <>
      <Link href="/history/1">Page 1</Link>
      <Link href="/history/2">Page 2</Link>
      <Link href="/history/3">Page 3</Link>
      <Link href="/history/4">Page 4</Link>
      <Link href="/history/5">Page 5</Link>

      <button onClick={clearHistory}>Clear History</button>

      <div>This is page {pageNumber}.</div>
      <div>Multi byte character: {multiByte}</div>
    </>
  )
}
