// packages/vue3/test-app/Pages/ClientSideVisit/Page1.vue
<script setup lang="ts">
import { router } from '@jamesst20/inertia-vue3'

defineProps<{
  foo: string
  bar: string
}>()

const replace = () => {
  router.replace({
    props: (props) => ({ ...props, foo: 'foo from client' }),
  })
}

const push = () => {
  router.push({
    url: '/client-side-visit-2',
    component: 'ClientSideVisit/Page2',
    props: {
      baz: 'baz from client',
    },
  })
}
</script>

<template>
  <div>{{ foo }}</div>
  <div>{{ bar }}</div>
  <button @click="replace">Replace</button>
  <button @click="push">Push</button>
</template>

// packages/react/test-app/Pages/ClientSideVisit/Page1.jsx
import { router } from '@jamesst20/inertia-react'

export default ({ foo, bar }) => {
  const replace = () => {
    router.replace({
      props: (props) => ({ ...props, foo: 'foo from client' }),
    })
  }

  const push = () => {
    router.push({
      url: '/client-side-visit-2',
      component: 'ClientSideVisit/Page2',
      props: { baz: 'baz from client' },
    })
  }

  return (
    <div>
      <div>{foo}</div>
      <div>{bar}</div>
      <button onClick={replace}>Replace</button>
      <button onClick={push}>Push</button>
    </div>
  )
}
