// packages/svelte/test-app/Pages/FormHelper/Dirty.svelte
<script>
  import { useForm } from '@jamesst20/inertia-svelte'

  const form = useForm({
    name: 'foo',
    foo: [],
  })

  const submit = () => {
    $form.post('')
  }

  const defaults = () => {
    $form.defaults()
  }

  const pushValue = () => {
    $form.foo.push('bar')
  }
</script>

<div>
  <div>
    Form is {#if $form.isDirty}dirty{:else}clean{/if}
  </div>
  <label>
    Full Name
    <input type="text" id="name" name="name" bind:value={$form.name} />
  </label>

  <button on:click={submit} class="submit">Submit form</button>
  <button on:click={defaults} class="defaults">Defaults</button>
  <button on:click={pushValue} class="push">Push value</button>
</div>

// packages/react/test-app/Pages/FormHelper/Dirty.jsx
import { useForm } from '@jamesst20/inertia-react'

export default (props) => {
  const form = useForm({ name: 'foo', foo: [] })

  const submit = () => {
    form.post('')
  }

  const defaults = () => {
    form.setDefaults()
  }

  const pushValue = () => {
    form.setData('foo', [...form.data.foo, 'bar'])
  }

  return (
    <div>
      <div>Form is {form.isDirty ? 'dirty' : 'clean'}</div>
      <label>
        Full Name
        <input
          type="text"
          id="name"
          name="name"
          onChange={(e) => form.setData('name', e.target.value)}
          value={form.data.name}
        />
      </label>

      <button onClick={submit} className="submit">
        Submit form
      </button>

      <button onClick={defaults} className="defaults">
        Defaults
      </button>

      <button onClick={pushValue}>Push Value</button>
    </div>
  )
}
