// packages/svelte/test-app/Pages/FormHelper/Errors.svelte
<script>
  import { useForm } from '@jamesst20/inertia-svelte'

  const form = useForm({
    name: 'foo',
    handle: 'example',
    remember: false,
  })

  const submit = () => {
    $form.post('/form-helper/errors')
  }

  const clearErrors = () => {
    $form.clearErrors()
  }

  const clearError = () => {
    $form.clearErrors('handle')
  }

  const setErrors = () => {
    $form.setError({
      name: 'Manually set Name error',
      handle: 'Manually set Handle error',
    })
  }

  const setError = () => {
    $form.setError('handle', 'Manually set Handle error')
  }
</script>

<div>
  <label>
    Full Name
    <input type="text" id="name" name="name" bind:value={$form.name} />
  </label>
  {#if $form.errors.name}
    <span class="name_error">{$form.errors.name}</span>
  {/if}
  <label>
    Handle
    <input type="text" id="handle" name="handle" bind:value={$form.handle} />
  </label>
  {#if $form.errors.handle}
    <span class="handle_error">{$form.errors.handle}</span>
  {/if}
  <label>
    Remember Me
    <input type="checkbox" id="remember" name="remember" bind:checked={$form.remember} />
  </label>
  {#if $form.errors.remember}
    <span class="remember_error">{$form.errors.remember}</span>
  {/if}

  <button on:click={submit} class="submit">Submit form</button>

  <button on:click={clearErrors} class="clear">Clear all errors</button>
  <button on:click={clearError} class="clear-one">Clear one error</button>
  <button on:click={setErrors} class="set">Set errors</button>
  <button on:click={setError} class="set-one">Set one error</button>

  <span class="errors-status">Form has {$form.hasErrors ? '' : 'no '}errors</span>
</div>

// packages/react/test-app/Pages/FormHelper/Errors.jsx
import { useForm } from '@jamesst20/inertia-react'

export default (props) => {
  const form = useForm({ name: 'foo', handle: 'example', remember: false })

  const submit = () => {
    form.post('/form-helper/errors')
  }

  const clearErrors = () => {
    form.clearErrors()
  }

  const clearError = () => {
    form.clearErrors('handle')
  }

  const setErrors = () => {
    form.setError({
      name: 'Manually set Name error',
      handle: 'Manually set Handle error',
    })
  }

  const setError = () => {
    form.setError('handle', 'Manually set Handle error')
  }

  return (
    <div>
      <label>
        Full Name
        <input
          type="text"
          id="name"
          name="name"
          onChange={(e) => form.setData('name', e.target.value)}
          value={form.data.name}
        />
      </label>
      {form.errors.name && <span className="name_error">{form.errors.name}</span>}
      <label>
        Handle
        <input
          type="text"
          id="handle"
          name="handle"
          onChange={(e) => form.setData('handle', e.target.value)}
          value={form.data.handle}
        />
      </label>
      {form.errors.handle && <span className="handle_error">{form.errors.handle}</span>}
      <label>
        Remember Me
        <input
          type="checkbox"
          id="remember"
          name="remember"
          onChange={(e) => form.setData('remember', e.target.checked)}
          checked={form.data.remember}
        />
      </label>
      {form.errors.remember && <span className="remember_error">{form.errors.remember}</span>}

      <button onClick={submit} className="submit">
        Submit form
      </button>

      <button onClick={clearErrors} className="clear">
        Clear all errors
      </button>
      <button onClick={clearError} className="clear-one">
        Clear one error
      </button>
      <button onClick={setErrors} className="set">
        Set errors
      </button>
      <button onClick={setError} className="set-one">
        Set one error
      </button>

      <span className="errors-status">Form has {form.hasErrors ? '' : 'no '}errors</span>
    </div>
  )
}
