// packages/react/test-app/Layouts/SiteLayout.jsx
import { usePage } from '@jamesst20/inertia-react'
import { useId, useState } from 'react'

export default ({ children }) => {
  const [createdAt, setCreatedAt] = useState(Date.now())

  window._inertia_layout_id = useId()
  window._inertia_site_layout_props = usePage().props

  return (
    <div>
      <span>Site Layout</span>
      <span>{createdAt}</span>
      <div>{children}</div>
    </div>
  )
}

// packages/vue3/test-app/Layouts/SiteLayout.vue
<script setup>
import { usePage } from '@jamesst20/inertia-vue3'
import { getCurrentInstance, onMounted, ref } from 'vue'

const createdAt = ref(null)

onMounted(() => {
  window._inertia_layout_id = getCurrentInstance().uid
  window._inertia_site_layout_props = usePage().props
  createdAt.value = Date.now()
})
</script>

<template>
  <div>
    <span>Site Layout</span>
    <span>{{ createdAt }}</span>
    <div>
      <slot />
    </div>
  </div>
</template>
