// packages/vue3/test-app/Pages/Poll/HookManual.vue
<script setup>
import { usePoll } from '@jamesst20/inertia-vue3'

const { start, stop } = usePoll(
  500,
  {
    only: ['custom_prop'],
    onFinish() {
      console.log('hook poll finished')
    },
  },
  {
    autoStart: false,
  },
)
</script>

<template>
  <button @click="start">Start</button>
  <button @click="stop">Stop</button>
</template>

// packages/react/test-app/Pages/Poll/HookManual.jsx
import { usePoll } from '@jamesst20/inertia-react'

export default () => {
  const { start, stop } = usePoll(
    500,
    {
      only: ['custom_prop'],
      onFinish() {
        console.log('hook poll finished')
      },
    },
    {
      autoStart: false,
    },
  )

  return (
    <>
      <button onClick={start}>Start</button>
      <button onClick={stop}>Stop</button>
    </>
  )
}
