// packages/svelte/test-app/Pages/Poll/HookManual.svelte
<script>
  import { usePoll } from '@jamesst20/inertia-svelte'

  const { start, stop } = usePoll(
    500,
    {
      only: ['custom_prop'],
      onFinish() {
        console.log('hook poll finished')
      },
    },
    {
      autoStart: false,
    },
  )
</script>

<button on:click={() => start()}>Start</button>
<button on:click={() => stop()}>Stop</button>

// packages/react/test-app/Pages/Poll/HookManual.jsx
import { usePoll } from '@jamesst20/inertia-react'

export default () => {
  const { start, stop } = usePoll(
    500,
    {
      only: ['custom_prop'],
      onFinish() {
        console.log('hook poll finished')
      },
    },
    {
      autoStart: false,
    },
  )

  return (
    <>
      <button onClick={start}>Start</button>
      <button onClick={stop}>Stop</button>
    </>
  )
}
