// packages/vue3/test-app/Pages/PersistentLayouts/RenderFunction/Nested/PageB.vue
<script>
import NestedLayout from '@/Layouts/NestedLayout.vue'
import SiteLayout from '@/Layouts/SiteLayout.vue'

export default {
  layout: (h, page) => {
    return h(SiteLayout, [h(NestedLayout, [page])])
  },
}
</script>

<script setup>
import { Link } from '@jamesst20/inertia-vue3'
</script>

<template>
  <div>
    <span class="text">Nested Persistent Layout - Page B</span>
    <Link href="/persistent-layouts/render-function/nested/page-a">Page A</Link>
  </div>
</template>

// packages/react/test-app/Pages/PersistentLayouts/RenderFunction/Nested/PageB.jsx
import NestedLayout from '@/Layouts/NestedLayout.jsx'
import SiteLayout from '@/Layouts/SiteLayout.jsx'
import { Link } from '@jamesst20/inertia-react'

const PageB = (props) => {
  return (
    <div>
      <span className="text">Nested Persistent Layout - Page B</span>
      <Link href="/persistent-layouts/render-function/nested/page-a">Page A</Link>
    </div>
  )
}

PageB.layout = (page) => {
  return (
    <SiteLayout>
      <NestedLayout children={page} />
    </SiteLayout>
  )
}

export default PageB
