// packages/react/test-app/Pages/Dump.jsx
import { usePage } from '@jamesst20/inertia-react'
import { useEffect } from 'react'

export default (props) => {
  const page = usePage()

  const dump = {
    headers: props.headers,
    method: props.method,
    form: props.form,
    files: props.files ? props.files : {},
    query: props.query,
    $page: page,
  }

  useEffect(() => {
    window._inertia_request_dump = {
      headers: props.headers,
      method: props.method,
      form: props.form,
      files: props.files ? props.files : {},
      query: props.query,
      $page: page,
    }
  }, [])

  return (
    <div>
      <div className="text">This is Inertia page component containing a data dump of the request</div>
      <hr />
      <pre className="dump">{JSON.stringify(dump, null, 2)}</pre>
    </div>
  )
}

// packages/vue3/test-app/Pages/Dump.vue
<script setup>
import { usePage } from '@jamesst20/inertia-vue3'
import { onBeforeMount } from 'vue'

const props = defineProps({
  headers: Object,
  method: String,
  form: Object,
  files: Array,
  query: Object,
})

const page = usePage()

const dump = {
  headers: props.headers,
  method: props.method,
  form: props.form,
  files: props.files ? props.files : {},
  query: props.query,
  $page: page,
}

onBeforeMount(() => {
  window._inertia_request_dump = {
    headers: props.headers,
    method: props.method,
    form: props.form,
    files: props.files ? props.files : {},
    query: props.query,
    $page: page,
  }
})
</script>

<template>
  <div>
    <div class="text">This is Inertia page component containing a data dump of the request</div>
    <hr />
    <pre class="dump">{{ dump }}</pre>
  </div>
</template>
