// packages/react/test-app/Pages/WhenVisible.jsx
import { WhenVisible } from '@jamesst20/inertia-react'
import { useState } from 'react'

const Foo = ({ label }) => {
  return <div>{label}</div>
}

export default () => {
  const [count, setCount] = useState(0)

  return (
    <>
      <div style={{ marginTop: '5000px' }}>
        <WhenVisible data="foo" fallback={<div>Loading first one...</div>}>
          <Foo label="First one is visible!" />
        </WhenVisible>
      </div>

      <div style={{ marginTop: '5000px' }}>
        <WhenVisible buffer={1000} data="foo" fallback={<div>Loading second one...</div>}>
          <Foo label="Second one is visible!" />
        </WhenVisible>
      </div>

      <div style={{ marginTop: '5000px' }}>
        <WhenVisible data="foo" fallback={<div>Loading third one...</div>} always>
          <Foo label="Third one is visible!" />
        </WhenVisible>
      </div>

      <div style={{ marginTop: '5000px' }}>
        <WhenVisible data="foo" fallback={<div>Loading fourth one...</div>}></WhenVisible>
      </div>

      <div style={{ marginTop: '6000px' }}>
        <WhenVisible
          fallback={<div>Loading fifth one...</div>}
          always
          params={{
            data: {
              count,
            },
            onSuccess: () => {
              setCount((c) => c + 1)
            },
          }}
        >
          <Foo label={`Count is now ${count}`} />
        </WhenVisible>
      </div>
    </>
  )
}

// packages/vue3/test-app/Pages/WhenVisible.vue
<script setup lang="ts">
import { WhenVisible } from '@jamesst20/inertia-vue3'
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <div style="margin-top: 5000px">
    <WhenVisible data="foo">
      <template #fallback>
        <div>Loading first one...</div>
      </template>

      <div>First one is visible!</div>
    </WhenVisible>
  </div>

  <div style="margin-top: 5000px">
    <WhenVisible :buffer="1000" data="foo">
      <template #fallback>
        <div>Loading second one...</div>
      </template>

      <div>Second one is visible!</div>
    </WhenVisible>
  </div>

  <div style="margin-top: 5000px">
    <WhenVisible data="foo" always>
      <template #fallback>
        <div>Loading third one...</div>
      </template>

      <div>Third one is visible!</div>
    </WhenVisible>
  </div>

  <div style="margin-top: 5000px">
    <WhenVisible data="foo">
      <template #fallback>
        <div>Loading fourth one...</div>
      </template>
    </WhenVisible>
  </div>

  <div style="margin-top: 6000px">
    <WhenVisible
      always
      :params="{
        data: {
          count,
        },
        onSuccess: () => {
          count += 1
        },
      }"
    >
      <template #fallback>
        <div>Loading fifth one...</div>
      </template>

      <div>Count is now {{ count }}</div>
    </WhenVisible>
  </div>
</template>
