// packages/vue3/test-app/Pages/PersistentLayouts/Shorthand/Nested/PageA.vue
<script>
import NestedLayout from '@/Layouts/NestedLayout.vue'
import SiteLayout from '@/Layouts/SiteLayout.vue'

export default {
  layout: [SiteLayout, NestedLayout],
}
</script>

<script setup>
import { Link, usePage } from '@jamesst20/inertia-vue3'
window._inertia_page_props = usePage().props
</script>

<template>
  <div>
    <span class="text">Nested Persistent Layout - Page A</span>
    <Link href="/persistent-layouts/shorthand/nested/page-b">Page B</Link>
  </div>
</template>

// packages/react/test-app/Pages/PersistentLayouts/Shorthand/Nested/PageA.jsx
import NestedLayout from '@/Layouts/NestedLayout.jsx'
import SiteLayout from '@/Layouts/SiteLayout.jsx'
import { Link, usePage } from '@jamesst20/inertia-react'

const PageA = (props) => {
  window._inertia_page_props = usePage().props

  return (
    <div>
      <span className="text">Nested Persistent Layout - Page A</span>
      <Link href="/persistent-layouts/shorthand/nested/page-b">Page B</Link>
    </div>
  )
}

PageA.layout = (page) => {
  return (
    <SiteLayout>
      <NestedLayout children={page} />
    </SiteLayout>
  )
}

export default PageA
