// packages/react/test-app/Pages/Dump.jsx
import { usePage } from '@jamesst20/inertia-react'
import { useEffect } from 'react'

export default (props) => {
  const page = usePage()

  const dump = {
    headers: props.headers,
    method: props.method,
    form: props.form,
    files: props.files ? props.files : {},
    query: props.query,
    $page: page,
  }

  useEffect(() => {
    window._inertia_request_dump = {
      headers: props.headers,
      method: props.method,
      form: props.form,
      files: props.files ? props.files : {},
      query: props.query,
      $page: page,
    }
  }, [])

  return (
    <div>
      <div className="text">This is Inertia page component containing a data dump of the request</div>
      <hr />
      <pre className="dump">{JSON.stringify(dump, null, 2)}</pre>
    </div>
  )
}

// packages/svelte/test-app/Pages/Dump.svelte
<script>
  import { beforeUpdate } from 'svelte'
  import { page } from '@jamesst20/inertia-svelte'

  export let headers
  export let method
  export let form
  export let files = {}
  export let query

  const dump = {
    headers,
    method,
    form,
    files,
    query,
    $page: $page,
  }

  beforeUpdate(() => {
    window._inertia_request_dump = {
      headers,
      method,
      form,
      files,
      query,
      $page: $page,
    }
  })
</script>

<div>
  <div class="text">This is Inertia page component containing a data dump of the request</div>
  <hr />
  <pre class="dump" style="white-space: pre-wrap; word-break: keep-all;">{JSON.stringify(dump)}</pre>
</div>
