// packages/react/test-app/Pages/ErrorModal.jsx
import { router } from '@jamesst20/inertia-react'

export default (props) => {
  const invalidVisit = () => {
    router.post('/non-inertia')
  }

  const invalidVisitJson = () => {
    router.post('/json')
  }

  return (
    <div>
      <span onClick={invalidVisit} className="invalid-visit">
        Invalid Visit
      </span>
      <span onClick={invalidVisitJson} className="invalid-visit-json">
        Invalid Visit (JSON response)
      </span>
    </div>
  )
}

// packages/svelte/test-app/Pages/ErrorModal.svelte
<script>
  import { router } from '@jamesst20/inertia-svelte'

  const invalidVisit = () => {
    router.post('/non-inertia')
  }

  const invalidVisitJson = () => {
    router.post('/json')
  }
</script>

<div>
  <span on:click={invalidVisit} class="invalid-visit">Invalid Visit</span>
  <span on:click={invalidVisitJson} class="invalid-visit-json">Invalid Visit (JSON response)</span>
</div>
