// packages/react/test-app/Pages/Visits/Location.jsx
import { router } from '@jamesst20/inertia-react'

export default (props) => {
  const locationVisit = (e) => {
    e.preventDefault()
    router.visit('/location')
  }

  return (
    <div>
      <span className="text">This is the page that demonstrates location visits</span>

      <a href="#" onClick={locationVisit} className="example">
        Location visit
      </a>
    </div>
  )
}

// packages/vue3/test-app/Pages/Visits/Location.vue
<script setup>
import { router } from '@jamesst20/inertia-vue3'

const locationVisit = (e) => {
  e.preventDefault()
  router.visit('/location')
}
</script>

<template>
  <div>
    <span class="text">This is the page that demonstrates location visits</span>

    <a href="#" @click="locationVisit" class="example">Location visit</a>
  </div>
</template>
