// packages/vue3/test-app/Layouts/Prefetch.vue
<script setup>
import { Link } from '@jamesst20/inertia-vue3'
</script>

<template>
  <div>
    <Link href="/prefetch/1" prefetch>On Hover (Default)</Link>
    <Link href="/prefetch/2" prefetch="mount">On Mount</Link>
    <Link href="/prefetch/3" prefetch="click">On Click</Link>
    <Link href="/prefetch/4" :prefetch="['hover', 'mount']" cacheFor="1s">On Hover + Mount</Link>
    <div>
      <slot />
    </div>
  </div>
</template>

// packages/svelte/test-app/Layouts/Prefetch.svelte
<script>
  import { inertia } from '@jamesst20/inertia-svelte'
</script>

<div>
  <a href="/prefetch/1" use:inertia={{ prefetch: true }}>On Hover (Default)</a>
  <a href="/prefetch/2" use:inertia={{ prefetch: 'mount' }}>On Mount</a>
  <a href="/prefetch/3" use:inertia={{ prefetch: 'click' }}>On Click</a>
  <a href="/prefetch/4" use:inertia={{ prefetch: ['hover', 'mount'], cacheFor: '1s' }}>On Hover + Mount</a>
  <div>
    <slot />
  </div>
</div>
