// packages/react/test-app/Layouts/SiteLayout.jsx
import { usePage } from '@jamesst20/inertia-react'
import { useId, useState } from 'react'

export default ({ children }) => {
  const [createdAt, setCreatedAt] = useState(Date.now())

  window._inertia_layout_id = useId()
  window._inertia_site_layout_props = usePage().props

  return (
    <div>
      <span>Site Layout</span>
      <span>{createdAt}</span>
      <div>{children}</div>
    </div>
  )
}

// packages/svelte/test-app/Layouts/SiteLayout.svelte
<script>
  import { onMount } from 'svelte'
  import { page } from '@jamesst20/inertia-svelte'

  let createdAt = null

  onMount(() => {
    window._inertia_layout_id = crypto.randomUUID()
    window._inertia_site_layout_props = $page.props
    createdAt = Date.now()
  })
</script>

<div>
  <span>Site Layout</span>
  <span>{createdAt}</span>
  <div>
    <slot />
  </div>
</div>
