// playgrounds/svelte/resources/js/Pages/Home.svelte
<script module>
  export { default as layout } from '../Components/Layout.svelte'
</script>

<script>
  import { inertia } from '@jamesst20/inertia-svelte'
  export let appName
</script>

<svelte:head>
  <title>Home - {appName}</title>
</svelte:head>

<h1 class="text-3xl">Home</h1>

<p class="mt-6">
  <a href="/article#far-down" use:inertia class="text-blue-700 underline">Link to bottom of article page</a>
</p>

// playgrounds/react/resources/js/Pages/Home.tsx
import { Head, Link } from '@jamesst20/inertia-react'
import Layout from '../Components/Layout'

const Home = () => {
  return (
    <>
      <Head title="Home" />
      <h1 className="text-3xl">Home</h1>
      <p className="mt-6">
        <Link href="/article#far-down" className="text-blue-700 underline">
          Link to bottom of article page
        </Link>
      </p>
    </>
  )
}

Home.layout = (page) => <Layout children={page} />

export default Home
