// packages/svelte/test-app/Pages/Links/AsWarningFalse.svelte
<script>
  import { inertia } from '@jamesst20/inertia-svelte'

  export let method
</script>

<div>
  <span class="text">This is the links page that demonstrates inertia-links without the 'as' warning</span>

  <button use:inertia={{ method, href: '/example' }} class="get">{method} button Link</button>
</div>

// packages/react/test-app/Pages/Links/AsWarningFalse.jsx
import { Link } from '@jamesst20/inertia-react'

export default ({ method }) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates inertia-links without the 'as' warning</span>

      <Link method={method} href="/example" className="get" as="button">
        {method} button Link
      </Link>
    </div>
  )
}
