// packages/vue3/test-app/Pages/Links/AsWarning.vue
<script setup>
import { Link } from '@jamesst20/inertia-vue3'

defineProps({
  method: String,
})
</script>

<template>
  <div>
    <span class="text">This is the links page that demonstrates inertia-links with an 'as' warning</span>

    <Link :method="method" href="/example" class="get">{{ method }} Link</Link>
  </div>
</template>

// packages/react/test-app/Pages/Links/AsWarning.jsx
import { Link } from '@jamesst20/inertia-react'

export default ({ method }) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates inertia-links with an 'as' warning</span>

      <Link method={method} href="/example" className="get">
        {method} Link
      </Link>
    </div>
  )
}
