// packages/svelte/test-app/Pages/Visits/AutomaticCancellation.svelte
<script>
  import { router } from '@jamesst20/inertia-svelte'

  const visit = () => {
    router.get(
      '/sleep',
      {},
      {
        onStart: () => console.log('started'),
        onCancel: () => console.log('cancelled'),
      },
    )
  }
</script>

<div>
  <span class="text">This is the page that demonstrates that only one visit can be active at a time</span>
  <a href="#" on:click={visit} class="visit">Link</a>
</div>

// packages/react/test-app/Pages/Links/AutomaticCancellation.jsx
import { Link } from '@jamesst20/inertia-react'

export default (props) => {
  return (
    <div>
      <span className="text">This is the links page that demonstrates that only one visit can be active at a time</span>
      <Link
        href="/sleep"
        className="visit"
        onCancel={() => console.log('cancelled')}
        onStart={() => console.log('started')}
      >
        Link
      </Link>
    </div>
  )
}
