// packages/svelte/test-app/Pages/Links/UrlFragments.svelte
<script>
  import { inertia } from '@jamesst20/inertia-svelte'

  let documentScrollTop = 0
  let documentScrollLeft = 0

  const handleScrollEvent = () => {
    documentScrollTop = document.documentElement.scrollTop
    documentScrollLeft = document.documentElement.scrollLeft
  }
</script>

<svelte:document on:scroll={handleScrollEvent} />

<div>
  <span class="text">This is the links page that demonstrates url fragment behaviour</span>
  <div style="width: 200vw; height: 200vh; margin-top: 50vh">
    <!-- prettier-ignore -->
    <div class="document-position">Document scroll position is {documentScrollLeft} & {documentScrollTop}</div>
    <a href="/links/url-fragments#target" use:inertia class="basic">Basic link</a>
    <a href="#target" use:inertia class="fragment">Fragment link</a>
    <a href="/links/url-fragments#non-existent-fragment" use:inertia class="non-existent-fragment"
      >Non-existent fragment link</a
    >

    <div id="target">This is the element with id 'target'</div>
  </div>
</div>

// packages/react/test-app/Pages/Links/UrlFragments.jsx
import { Link } from '@jamesst20/inertia-react'
import { useEffect, useState } from 'react'

export default (props) => {
  const [documentScrollTop, setDocumentScrollTop] = useState(0)
  const [documentScrollLeft, setDocumentScrollLeft] = useState(0)

  useEffect(() => {
    document.addEventListener('scroll', handleScrollEvent)
  })

  const handleScrollEvent = () => {
    setDocumentScrollTop(document.documentElement.scrollTop)
    setDocumentScrollLeft(document.documentElement.scrollLeft)
  }

  return (
    <div>
      <span className="text">This is the links page that demonstrates url fragment behaviour</span>
      <div style={{ width: '200vw', height: '200vh', marginTop: '50vh' }}>
        {/* prettier-ignore */}
        <div className="document-position">
          Document scroll position is {documentScrollLeft} & {documentScrollTop}
        </div>
        <Link href="/links/url-fragments#target" className="basic">
          Basic link
        </Link>
        <Link href="#target" className="fragment">
          Fragment link
        </Link>
        <Link href="/links/url-fragments#non-existent-fragment" className="non-existent-fragment">
          Non-existent fragment link
        </Link>

        <div id="target">This is the element with id 'target'</div>
      </div>
    </div>
  )
}
