// packages/svelte/test-app/Pages/DeferredProps/Page2.svelte
<script>
  import { Deferred } from '@jamesst20/inertia-svelte'

  export let baz
  export let qux
</script>

<Deferred data="baz">
  <div slot="fallback">Loading baz...</div>
  {baz}
</Deferred>

<Deferred data="qux">
  <div slot="fallback">Loading qux...</div>
  {qux}
</Deferred>

<Deferred data={['baz', 'qux']}>
  <div slot="fallback">Loading baz and qux...</div>
  both {baz} and {qux}
</Deferred>

// packages/vue3/test-app/Pages/DeferredProps/Page2.vue
<script setup lang="ts">
import { Deferred } from '@jamesst20/inertia-vue3'

defineProps<{
  baz?: string
  qux?: string
}>()
</script>

<template>
  <Deferred data="baz">
    <template #fallback>
      <div>Loading baz...</div>
    </template>
    {{ baz }}
  </Deferred>

  <Deferred data="qux">
    <template #fallback>
      <div>Loading qux...</div>
    </template>
    {{ qux }}
  </Deferred>

  <Deferred :data="['baz', 'qux']">
    <template #fallback>
      <div>Loading baz and qux...</div>
    </template>
    both {{ baz }} and {{ qux }}
  </Deferred>
</template>
