// packages/react/test-app/Pages/PersistentLayouts/Shorthand/Simple/PageA.jsx
import SiteLayout from '@/Layouts/SiteLayout'
import { Link, usePage } from '@jamesst20/inertia-react'

const PageA = (props) => {
  window._inertia_page_props = usePage().props

  return (
    <div>
      <span className="text">Simple Persistent Layout - Page A</span>
      <Link href="/persistent-layouts/shorthand/simple/page-b">Page B</Link>
    </div>
  )
}

PageA.layout = (page) => <SiteLayout children={page} />

export default PageA

// packages/vue3/test-app/Pages/PersistentLayouts/Shorthand/Simple/PageA.vue
<script>
import Layout from '@/Layouts/SiteLayout.vue'

export default {
  layout: Layout,
}
</script>

<script setup>
import { Link, usePage } from '@jamesst20/inertia-vue3'

window._inertia_page_props = usePage().props
</script>

<template>
  <div>
    <span class="text">Simple Persistent Layout - Page A</span>
    <Link href="/persistent-layouts/shorthand/simple/page-b">Page B</Link>
  </div>
</template>
