// packages/svelte/test-app/Pages/PersistentLayouts/Shorthand/Simple/PageA.svelte
<script module>
  import SiteLayout from '@/Layouts/SiteLayout.svelte'

  export const layout = SiteLayout
</script>

<script>
  import { inertia, page } from '@jamesst20/inertia-svelte'

  window._inertia_page_props = $page.props
</script>

<div>
  <span class="text">Simple Persistent Layout - Page A</span>
  <a href="/persistent-layouts/shorthand/simple/page-b" use:inertia>Page B</a>
</div>

// packages/vue3/test-app/Pages/PersistentLayouts/Shorthand/Simple/PageA.vue
<script>
import Layout from '@/Layouts/SiteLayout.vue'

export default {
  layout: Layout,
}
</script>

<script setup>
import { Link, usePage } from '@jamesst20/inertia-vue3'

window._inertia_page_props = usePage().props
</script>

<template>
  <div>
    <span class="text">Simple Persistent Layout - Page A</span>
    <Link href="/persistent-layouts/shorthand/simple/page-b">Page B</Link>
  </div>
</template>
